### PR TITLE
Enhances Maps Links by adding new DTS for Direct Navigation Links

### PR DESCRIPTION
**Pull request by billyjbryant**
## Description
This change restores the old mechanism of the prior `<gmaps>` DTS which directed you to a static map rather than immediately starting navigation. The next change introduces new `<Xnav>` DTS fields which start direct navigation in the platform of choice. 

### New DTS created:
|DTS|Function|
|-|-|
|`<gnav>`|Begins navigation to the event using Google Maps|
|`<applenav>`|Begins navigation to the event using Apple Maps|
|`<wazenav>`|Begins navigation to the event using Waze|

### Updated DTS:
|DTS|Previous Function|New Function|
|-|-|-|
|`<gmaps>`|Begins navigation to the event using Google Maps|Opens a static map centered on the event in Google Maps|
|`<applemaps>`|Begins navigation to the event using Apple Maps|Opens a static map centered on the event in Apple Maps|
|`<waze>`|Begins navigation to the event using Waze|Opens a static map centered on the event in Waze
* `<gmaps>` change is to restore it to its prior functionality before #789 which changed Google Maps to be direct navigation to bring it in-line with the other two DTS options.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (would cause existing functionality to change)

## Motivation and Context
There was concern over the change to how Google Maps links worked and the unexpected nature of now taking the user directly into navigation rather than just linking to the location of the event. 

## How Has This Been Tested?
Testing not yet performed, will ask users in Beta chat to test. 

## Wiki Update

- [x] This change requires an update to the Wiki.
- [ ] This change does not require an update to the Wiki.

### CODE REVIEW

**Comment by Audidriver13** [comment]
Unfortuately the standard gmaps link doesn't work anymore. The Link is now following: https://www.google.de/maps/search/?api=1&destination=52.58123%2C13.2853 (that does't work)

**Comment by billyjbryant** [comment]
> Unfortuately the standard gmaps link doesn't work anymore. The Link is now following: https://www.google.de/maps/search/?api=1&destination=52.58123%2C13.2853 (that does't work)

@Audidriver13 : I Fixed this in the latest push, please test.

**Comment by Audidriver13** [comment]
> > Unfortuately the standard gmaps link doesn't work anymore. The Link is now following: https://www.google.de/maps/search/?api=1&destination=52.58123%2C13.2853 (that does't work)
> 
> @Audidriver13 : I Fixed this in the latest push, please test.

Now it works like a charm :)

**Comment by billyjbryant** [comment]
@LegitDongo can you review and approve this?

**Review by LegitDongo — APPROVED** [review]
Checked it all, looks good

**Pull request merged**
