### PR TITLE
Telegram: enable web page preview by default

### PR DESCRIPTION
**Pull request by Alexus230**
## Description
This PR enable by default web page preview for Telegram alarms.

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Motivation and Context
This PR return old behavior (prior 3.6 patch)

## How Has This Been Tested?

Tested on my PokeAlarm instance.

## Wiki Update

- [ ] This change requires an update to the Wiki.
- [x] This change does not require an update to the Wiki.

## Checklist
- [x] This change follows the code style of this project.
- [x] This change only changes what is necessary to the feature.

### CODE REVIEW

**Comment by kvangent** [comment]
What is the reason you want this? This was disable intentionally because Telegram started showing the preview for gmaps links and everyone was complaining.

**Comment by Alexus230** [comment]
In our community not everyone knows what pokemon looks like. So I use this web_page_preview as some sort of hack to reduce messages. 

Here how it looks like:
default

**Comment by kvangent** [comment]
I'm open to adding a toggle for it (similar to sticker or map notify), but I think we need to need to leave it disabled by default.

**Comment by billyjbryant** [comment]
I agree with disabling this by default and adding a toggle in the alert definition to enable it.

**Comment by Alexus230** [comment]
Could you please add a toogle? Am I need to open an issue with this feature request?

**Comment by MARTINI1** [comment]
I don't understand this use of the preview, if you want to show images use the avatar_url or the icon_url

**Comment by Alexus230** [comment]
@MARTINI1

Unfortunately, I can't find this options in documentation: [Telegram](https://github.com/PokeAlarm/PokeAlarm/wiki/Telegram). I dont know how this functions must work in Telegram messages.

**Comment by MARTINI1** [comment]
@Alexus230 is in the documentation, use the stickers and if you want to use your own, change the path in stickers_urlm is in the advanced config table

https://github.com/PokeAlarm/PokeAlarm/wiki/Telegram#advanced-config

**Comment by Alexus230** [comment]
@MARTINI1

I've already read documentation. In my setup I use web page preview to reduce amount of messages. If stickers enabled i get 3 messages on every event: stiker, text messag and map.

**Comment by kvangent** [comment]
@Alexus230 If you want to open an Issue to request it you may, or else you are welcome to PR the change yourself. I'll close this for now, feel free to reopen if you decide to PR.

**Pull request closed without merging**
