### PR TITLE
gostadium-like implementation of stat-product-percentage for PvP

### PR DESCRIPTION
**Pull request by crhbetz**
## Description
PvP-relevant calculation of percentage of perfect stat product for great and ultra league, basically an implementation of the things that https://gostadium.club/pvp/iv does.

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Motivation and Context
It's needed because PvP is becoming a more relevant part of Pokemon Go, and great-league and ultra-league PvP don't really care about the traditional "the more IV, the better" logic. 

With filters based on this change, you can find Pokemon who reach a desired percentage of the highest possible stat product. It'll consider all possible evolutions of the Pokemon and output the best result per league, with resulting percentage, CP and level. It'll also respect the fact that you can't downgrade a Pokemon to fit into a lower league. It can also build a link to the gostadium view for the Pokemon with the exact IV values.

### Attention - ugly code!

I know that the code in this state is not PEP8 compliant and just really ugly. I'm not a programming pro by any means and just wanted to put this out there as a response to https://github.com/PokeAlarm/PokeAlarm/issues/703 - I had intended for this tinkering to remain in private, expecting someone else would come up with something more sophisticated soon, and that's what the code looks like I guess. It's the best I was able to come up with.

## How Has This Been Tested?

Poorly. Me and another guy doing some random checks against the gostadium link it'll build, looking good so far. I'm planning to make it public on my services soon.

## Wiki Update

- [x] This change requires an update to the Wiki. _since it's a new feature, I guess._
- [ ] This change does not require an update to the Wiki.

### CODE REVIEW

**Comment by LegitDongo** [comment]
Are the requirements for better master league mons similar to great and ultra league requirements?

I don't know much about PvP

**Comment by crhbetz** [comment]
Master league mons should be perfect at 15/15/15, as there's no CP cap.

The theory for the capped leagues is that in order to have the advantage in a majority of matchups, you want the highest possible stat product (because total damage output [TDO] scales with stat product).

With ATK being more weighted in CP calculation than DEF and STA, you'll want low ATK and high DEF and STA in capped leagues because that way you can cram more stat product below the CP cap.

None of this is relavant in master league, because there's no cap to fit under.

**Comment by LegitDongo** [comment]
This makes sense, thanks for the explanation.

Test coming soon and proper review as well.

**Comment by crhbetz** [comment]
Sorry for kinda messing up the git history there ... noob at work :-)

Also it should be noted that this PR can't currently identify and subsequently skip impossible evolutions like when evolutions are based on gender. It'll still use the best available evolved form even if the reported mon can't actually evolve to it.

**Comment by LegitDongo** [comment]
What is the purpose of `tools/pvp.py`?
It looks like it prints out a giant list

Edit: Answered on Discord
```
Do you have calculate the product with the old values or do you copied from somewhere else without calculating?
Calculated. I'll provide th script
```

**Review by BadWolf0081 — DISMISSED** [review]
The link to go stadium is great, a way to give a link without displaying the entire URL would be cleaner.  Other then that this functions fine.

EDIT:  Discovered how to make the info link showup as a simple "PVP Info" button, works amazing.

**Comment by LegitDongo** [comment]
@crhbetz do you want to resolve the base_stats conflicts?

**Comment by crhbetz** [comment]
- resolved base_stats conflict
- removed duplicate code from tools/pvp.py as discussed on discord
- made the git history even messier

Been running this feature over two weeks now. No complaints, only happy users. It looks working and ready to me, so I'll only make more changes if someone finds any bugs or issues.

**Comment by LucianoNeo** [comment]
A filter by PVP target mon name would be awesome! 
Congratulations for the excelent work!

**Comment by JimBim89** [comment]
Works great, I also request filter for target mon.

**Comment by x3r0x** [comment]
- There is an error getting the gostadium link at least for mons with a space in its name like mr. mime. The dot should be converted to a plus.

- Some evolutions of evee are not obtainable at the current state of the game and therefore should be excluded.

Also I would like to have a link for pvpoke, which causes new issues, like different forms depending on weather (castform) or location (gastrodon).

> 'great_pvpoke': ("https://pvpoke.com/rankings/all/1500/overall/{}/"                     ).format(locale.get_english_pokemon_name(self.great_id).lower()),

Another idea would be to calculate the candy and stardust you need to reach the lvl

**Comment by Jay1175** [comment]
Can the SP calculation be reworked to include level 41 (perhaps optionally)?

I've been informed that the 8/15/15 Marill that was output as 100% SP is outdated and 7/15/13 would have higher stats at level 41 than the 8/15/15 would have at level 40.

**Comment by marcb1387** [comment]
Can we add the gostadium Rank as a DTS ?

**Comment by bbdoc** [comment]
Hello.

I'm looking at implementing this PR but was wondering how to create a different alarm for PVP. Currently I have a discord section and a telegram section, and under each section I have a monsters section. I don't want to use the same monster section for alerting PVP as I want to use some of the new DTS this PR allows for. How do you achieve that ? Should I create 2 separate discord/telegram sections only for the sake of PVP or is there a way to add specific sections like pvp1500 and pvp2500 under my existing discord/telegram sections ?

Thanks

**Comment by LegitDongo** [comment]
@bbdoc you can use PVP DTS anywhere IV scans work
However, if you only want mons that pass your PVP filters to have a certain alarm, you will have to use rules.

Most people have a different alarm for PVP specifically since the rest of the information (normal IV scan stuff) doesn't benefit users anyway

**Comment by bbdoc** [comment]
@crhbetz Looks like I found a bug... <great_mon_name> and <ultra_mon_name> are resolving correctly towards Telegram, but not towards discord...

**Review by bbdoc — DISMISSED** [review]
I have been running this PR for one month now, runs perfectly, didn't notice any issue. Can be merged in my opinion.

**Comment by LegitDongo** [comment]
OK guys, I know this has been a long time coming, but here's a few things I've been working on here
1. `great_pvpoke` and `ultra_pvpoke` - these will link to pvpoke for that mon (thanks @x3r0x )
2. `great_url` and `ultra_url` fixes for special monsters (such as Mr. Mime and Farfetch'd) (thanks @x3r0x )
3. Code cleanup - a review here would be awesome if anybody would look at it :)
4. Tests!

**This needs some testing!!** So please let me know if anything is off :)

I've been trying to get the target mon filter implemented but it's been far more difficult than I originally anticipated.

Replies:
@marcb1387 We can't add the rank that gostadium gives without doing an additional request and slowing down the whole life-cycle entirely
@Jay1175 If I had the calculations for > level 40 then that would be something that can be considered in the future.

**Comment by JabLuszko** [comment]
I would like `utltra_mon_id` and `great_mon_id` (and form/costume, yeah :D), so for avatar/url we can use the 'outcome' mon, not the basic wild one.

**Comment by acocalypso** [comment]
link for gostadium has changed to https://www.stadiumgaming.gg/rank-checker

**Review by acocalypso — DISMISSED** [review]
no issues found so far

**Review by LegitDongo — APPROVED** [review]
More features to come later
Gonna merge while this is still good

**Pull request merged**
