### PR TITLE
Full PVP support for level 50 and Gen6

### PR DESCRIPTION
**Pull request by Audidriver13**
## Description

- Updated base_stats and cp_multiplier for level 50 (Thanks @Devreugkx and @ggNovelty !)
- changed all relevant files to support pvp level 50

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Motivation and Context

Now that Generation 6 is available and the monsters can be pushed to level 50, PvP must be adjusted accordingly.

## How Has This Been Tested?

- works perfectly on own system
- Stats were checked with popular pvp calculators (pvpoke.com and pogostat.com)

## Wiki Update

- [ ] This change requires an update to the Wiki.
- [x] This change does not require an update to the Wiki.

### CODE REVIEW

**Comment by ggNovelty** [comment]
Regarding the changes to cp_multipliers.json:

From what I have gathered, the exact CP Multipliers are still unknown. While the Game Master does provide CPM values, those are actually truncated versions of the actual values which are not exposed to the client. While the GM values are 'good enough' for the vast majority of calculations, there are a few edge cases in which their calculations will be incorrect. This could hypothetically result in a Pokemon calculated by PA to hit *500 CP to actually level up to *501. 

The community has reverse engineered the values to a few more decimal places. While we still don't know the exact values, by using more precise values we reduce the chances that an edge case should occur. 

I think the previous values were more precise for levels 1-40, and I used this source for the values from 40.5 - 51

Source : https://old.reddit.com/r/TheSilphRoad/comments/jwjbw4/level_4550_expected_cpms_based/

**Comment by Audidriver13** [comment]
I will take the new values from your source and calculate the base_stats again. The reddit user celandro (better known as the developer of Pokebattler) seems to me to be a very trustworthy source. Thanks @ggNovelty

**Comment by Audidriver13** [comment]
Calculation done. Hopefully everything should be just right now :)

**Comment by ColdShadow80** [comment]
Working well. Gen6 stats seem fixed and posts are being sent based on level 50

**Comment by ColdShadow80** [comment]
Any reason this PR is not being merged?

**Review by goldjpg — APPROVED** [review]

**Review by Axiangel — APPROVED** [review]
Been running this for a few days now. Neither me or any in my community have noticed anything off.  Everything seems good to go! ^^

**Review by LegitDongo — APPROVED** [review]
Thanks for the comments guys ❤️

**Pull request merged**
