### PR TITLE
Fixed weather/severity event issues

### PR DESCRIPTION
**Pull request by JimBim89**
## Description
This fixes the issues with the or statement related to 0 ids.

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Motivation and Context
Fixes for issue https://github.com/PokeAlarm/PokeAlarm/issues/691

## How Has This Been Tested?
Locally with latest dev.

## Wiki Update

- [ ] This change requires an update to the Wiki.
- [x] This change does not require an update to the Wiki.

### CODE REVIEW

**Comment by JimBim89** [comment]
While digging through weather stuff I also noticed that PA has serverity "extreme" as 3, but in the protos it has a value of 2 ([link](https://github.com/Furtif/POGOProtos/blob/master/src/POGOProtos/Map/Weather/WeatherAlert.proto)), does someone know why its one off here? 

Also the text for "moderate" is never mentioned like that to the player in game, the weather alert is always displayed as "Careful", maybe adjust the locales to reflect the ingame behavior?

**Review by kvangent — DISMISSED** [review]

**Comment by kvangent** [comment]
> While digging through weather stuff I also noticed that PA has serverity "extreme" as 3, but in the protos it has a value of 2 ([link](https://github.com/Furtif/POGOProtos/blob/master/src/POGOProtos/Map/Weather/WeatherAlert.proto)), does someone know why its one off here?
> 
> Also the text for "moderate" is never mentioned like that to the player in game, the weather alert is always displayed as "Careful", maybe adjust the locales to reflect the ingame behavior?

The protos may have shifted, or we may have gotten it wrong in the first place. Happy to update if you want to PR it.

**Review by LegitDongo — DISMISSED** [review]
This doesn't fix the underlying issue of `or` usage, however this fixes the immediate bug of weather being broken.

**Comment by LegitDongo** [comment]
Waiting on merge until we can get a few more weather-related things put into this

**Comment by LegitDongo** [comment]
@JimBim89 Here's the changes we discussed on Discord, did you want to add these here?
```
for severity it would error like mentioned avbove (can't shift unknown to 3 digits)
and for ingame weather disabled it wouldn't get the localized weather word for 0 (None)
whats still up for discussion is the id for extreme weather and the locals for moderate - in PA extreme is 3 but in protos its 2
and would you rather have the old "Moderate" text from protos var or the ingame text "Careful" for id 1?
```

We also discussed a better way to alert weather changes since severity can change several times a minute, such as a cooldown
`maybe a cooldown (1-5min?) after a severity change`
https://cdn.discordapp.com/attachments/218822834225545216/656562725882822722/Unbenannt.png

**Review by LegitDongo — APPROVED** [review]
Since this still fixes the bug I'm going to go ahead and merge this.

If you still want to add the mentioned functionality later you can open a new PR

**Pull request merged**
