### PR TITLE
optimize Alarm.replace()

### PR DESCRIPTION
**Pull request by sprintnudel**
The loop is very inefficient with the evergrowing number of DTS values. By using a one-pass regex substitution the method is ~ 10x faster.

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Motivation and Context

Profiling the (Telegram) alarm generation the high number of str.replace() and str.format() calls jumped into my eyes.
While this was no dealbreaker in the sense that it takes too long in a reasonable setup, I still couldn't live with this. With my test json resulting in 999 alarms the cumulative runtime can be brought down by one magnitude using regex:
```
   #ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     #4995    1.128    0.000    1.907    0.000 Alarm.py:77(replace)

   #ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     #4995    0.011    0.000    0.182    0.000 Alarm.py:78(replace)
```

## How Has This Been Tested?

Measurements with cProfile

## Wiki Update

- [ ] This change requires an update to the Wiki.
- [x] This change does not require an update to the Wiki.

### CODE REVIEW

**Comment by sprintnudel** [comment]
Note that this currently conflicts with #869. Which is merged first forces the other to resolve the conflict I guess.

**Comment by sprintnudel** [comment]
Runs on my instance, since this PR was published. No complaints so far.

**Comment by Pontiky** [comment]
The discord webhooks formatted to ping a discord role don't work anymore. Pings are formatted like that: `<@123456789>` and it now simply disappears in the webhook text.

I suspect this PR so we need to deep a bit more to confirm that.

**Comment by sprintnudel** [comment]
> The discord webhooks formatted to ping a discord role don't work anymore. Pings are formatted like that: `<@123456789>` and it now simply disappears in the webhook text.

Should be fixed now.

**Comment by Pontiky** [comment]
> > The discord webhooks formatted to ping a discord role don't work anymore. Pings are formatted like that: `<@123456789>` and it now simply disappears in the webhook text.
> 
> Should be fixed now.

It now works properly 👍

**Comment by LegitDongo** [comment]
This will give some false positives; it won't replace anything, but we can do less work by fixing it
That being said, we might mess up someone's character formatting if we don't fix this
examples:
`<<1>` 
`<<<<<<<<>`
`<3<<>`
this also matches newlines:
```
<
a>
```

`<([^<>\n]+)>` should be an appropriate regex

note: I'm not sure if I tested *every* possibility 😄

**Review by LegitDongo — CHANGES_REQUESTED** [review]
marking this appropriately, see above comment

**Comment by d12fk** [comment]
> `<([^<>\n]+)>` should be an appropriate regex

done

**Comment by sprintnudel** [comment]
> `<([^<>\n]+)>` should be an appropriate regex

done

**Comment by billyjbryant** [comment]
@LegitDongo is your concerns with this PR resolved now?

**Review by billyjbryant — APPROVED** [review]

**Review by LegitDongo — APPROVED** [review]
haven't tested latest, but seems fine

**Pull request merged**
