### PR TITLE
Black Formatting

### PR DESCRIPTION
**Pull request by LegitDongo**
## Description
[Black](https://github.com/psf/black) is an opinionated code formatter

This increases the character limit per line to 88, as well as sets up a standard for formatting

See [the black docs](https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#line-length) on why I added extend-ignore for E203 in `.flake8`, this makes it so line limits aren't mega strict on 88 characters

For code in the future, once black is installed, you can simply run `black .` (for current folder) to format any python it finds

## Type of Change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Motivation and Context
Nicer line limits and formatting, easier to work with

## How Has This Been Tested?
Locally

## Wiki Update
- [ ] This change requires an update to the Wiki.
- [x] This change does not require an update to the Wiki.

### CODE REVIEW

**Comment by billyjbryant** [comment]
Look into building Black formatting into unit tests so that it can be done by running the test suite :)

**Review by Pontiky — APPROVED** [review]
It's a great improvement for the readability of the code!

I tested this PR for 3 days now on a live configuration and I don't have any bug to report.

**Comment by billyjbryant** [comment]
Needs to be rebased

**Comment by billyjbryant** [comment]
@LegitDongo can you rebase and resolve merge conflicts?

**Comment by LegitDongo** [comment]
gave this a test, seems fine; shouldn't be anything breaking anyway

**Comment by Pontiky** [comment]
I'm using it since early November. Everything is working.

**Pull request merged**
