### PR TITLE
Pvp fix hashtag

### PR DESCRIPTION
**Pull request by Devreugkx**
## Description

Changed Generation 6 base stats as they were outdated.
Changed cp_multipliers to more accurate versions, ones that are also used by major pvp_websites
Changed max stat products for GL and UL accordingly.
Fixed two errors that were present in my previous PR

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Motivation and Context
Some data was outdated or could have been more updated/accurate

## How Has This Been Tested?
Hand picked and tested some Pokémon

## Wiki Update

- [ ] This change requires an update to the Wiki.
- [x] This change does not require an update to the Wiki.

### CODE REVIEW

**Comment by LucianoNeo** [comment]
Missing a last **}** 
in base stats

**Comment by Devreugkx** [comment]
> Missing a last **}**
> in base stats

Fixed it

**Comment by JimBim89** [comment]
FIle paths are wrong? Should be in the data folder or not?

**Comment by Devreugkx** [comment]
All my commits have been combined in PR#753, so closing this one.

**Pull request closed without merging**
