### PR TITLE
fix/hack for Slack static google maps images not showing

### PR DESCRIPTION
**Pull request by elincognito**
## Description

This PR can be seen as an hack, however currently there is no other solution that i am aware.
This works by setting all links in slack to unfurl by default and appending the gmaps url
to the end of slack text.

One can test message building [here](https://api.slack.com/docs/messages/builder?msg=%7B%22username%22%3A%22Swablu%22%2C%22unfurl_links%22%3Atrue%2C%22text%22%3A%22bl%C3%A1%20bl%C3%A1%20bl%C3%A1%20%3Chttps%3A%2F%2Fmaps.googleapis.com%2Fmaps%2Fapi%2Fstaticmap%3Fsize%3D512x512%26zoom%3D15%26center%3DBrooklyn%26style%3Dfeature%3Aroad.local%257Celement%3Ageometry%257Ccolor%3A0x00ff00%26style%3Dfeature%3Alandscape%257Celement%3Ageometry.fill%257Ccolor%3A0x000000%26style%3Delement%3Alabels%257Cinvert_lightness%3Atrue%26style%3Dfeature%3Aroad.arterial%257Celement%3Alabels%257Cinvert_lightness%3Afalse%26key%3DAIzaSyDTElUvfW04L1zHbLb0jdQndEXzas4W4v4%7C%20%3E%22%2C%22attachments%22%3A%5B%7B%22fallback%22%3A%22Map_Preview%22%2C%22image_url%22%3A%22https%3A%2F%2Fmaps.googleapis.com%2Fmaps%2Fapi%2Fstaticmap%3Fsize%3D512x512%26zoom%3D15%26center%3DBrooklyn%26style%3Dfeature%3Aroad.local%257Celement%3Ageometry%257Ccolor%3A0x00ff00%26style%3Dfeature%3Alandscape%257Celement%3Ageometry.fill%257Ccolor%3A0x000000%26style%3Delement%3Alabels%257Cinvert_lightness%3Atrue%26style%3Dfeature%3Aroad.arterial%257Celement%3Alabels%257Cinvert_lightness%3Afalse%26key%3DAIzaSyDTElUvfW04L1zHbLb0jdQndEXzas4W4v4%22%7D%5D%2C%22channel%22%3A%22example%22%7D)

## Type of Change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Wiki Update

- [ ] This change requires an update to the Wiki.
- [ ] This change does not require an update to the Wiki.

## Checklist
- [ ] This change follows the code style of this project.
- [ ] This change only changes what is necessary to the feature.

### CODE REVIEW

**Comment by kvangent** [comment]
As a warning to anyone considering using this: It will show your GMaps key to the world.

**Comment by billyjbryant** [comment]
I would say the fact that this exposes gmaps key makes this PR unsafe to use.  We should come up with a better solution than this hack.

**Comment by elincognito** [comment]
@billyjbryant  @kvangent I know this is an hack, the other only solution i can think about is having a server fetching the gmaps images locally onto the user host and serve those images, that way the gmaps key would stay private.

**Comment by kvangent** [comment]
We are better off remove static maps from Slack than implementing this change as is. 

I'm going to close this, and direct continued discussion of this problem to https://github.com/PokeAlarm/PokeAlarm/issues/644.

**Pull request closed without merging**
