### PR TITLE
New shadow forms & Normal forms

### PR DESCRIPTION
**Pull request by LegitDongo**
## Description
It adds normal forms where shadows were made, adds shadow, purified, and "NoEvolve" forms for good measure.

Without the normal forms it would cause images to 404
Some may also want the shadow/purified images

## Type of Change
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (would cause existing functionality to change)

## Motivation and Context
Add forms for new mons

## How Has This Been Tested?
None

## Wiki Update
- [ ] This change requires an update to the Wiki.
- [x] This change does not require an update to the Wiki.

### CODE REVIEW

**Review by JimBim89 — DISMISSED** [review]
German looks fine.

**Comment by darkelement1987** [comment]
Use 'kappe' for 'cap' in German translation. Cap is English not German.

**Review by kvangent — DISMISSED** [review]

**Comment by darkelement1987** [comment]
Seems to work fine

image

**Review by darkelement1987 — APPROVED** [review]
image

**Review by darkelement1987 — COMMENTED** [review]
Fall 2019 Forms also working:

image

**Review by darkelement1987 — DISMISSED** [review]

**Review by kvangent — APPROVED** [review]

**Pull request merged**
