### PR TITLE
New Filters Rework

### PR DESCRIPTION
**Pull request by kvangent**
This is the implementation of the new filters rework. Filter's have changed significantly. There are now the following 5 sections. Each has `enabled`, `defaults`, and `filters` subsections. `enable` can be either true or false. `defaults` are parameters that are automatically applied to all filters, unless overrode in that specific filter. `filters` is a list of name -> filters that decided which events get notified.

It's also worth noting that `missing_info` is fundamentally different from `ignore_missing` - when a filter is checking an event, it will skip any parameters that are unknown. If iv info is missing and `min_iv` is set, `missing_info` will allow it if `true` and reject if `false`.

Geofences have also changed - they are no longer checked for every filter. Instead each filter has a `geofences` section in which a list of geofence names can be listed. Filters will only check the geofences they have been assigned. 

Another new change is `customer_dts`. With this parameter, you can add a map of key-value pairs that act as custom DTS for that filter. With `"custom_dts": { "key1": "value1", "key2": "value2" }`, `<key1>` would be replaced as `value1`. 

The is a significant change that will break older configs, so don't try it out if you don't have time. There are numerous DTS changes as well, so it's recommended you use the Webhook Tester to ensure things are working as intended. 

**!!! Warning !!!**: This feature is still new, so make sure to keep back ups of your older configs in case you run into problems. 

### Monsters

**filters**
```json
"monsters":{
        "enabled": true,
        "defaults": {
        },
        "filters": {
            "filter-name": {
                "monsters": [ "Bulbasaur", 2, 3 ],
                "min_dist": 0, "max_dist": "inf",
                "min_lvl": 0, "max_lvl": 40, "min_atk": 0, "max_atk": 15,
                "min_def": 0, "max_def": 15, "min_sta": 0, "max_sta": 15,
                "min_iv": 0.0, "max_iv": 100,
                "form_ids": [ 0 ],
                "quick_moves": [ "Vine Whip", "Tackle"],
                "charge_moves": [ "Sludge Bomb", "Seed Bomb"],
                "genders": [ "male", "female", "neutral"],
                "min_height": 0, "max_height": "inf",
                "min_weight": 0, "max_weight": "inf",
                "sizes": [ "tiny", "small", "normal", "large", "big" ],
                "geofences": [ "Central Park" ],
                "custom_dts": { "key1": "value1", "key2": "value2" },
                "missing_info": false
            }
        }
    },
```

**dts**
```
'encounter_id', 'mon_name', mon_id', 'mon_id_3', time_left', '12h_time',  
'24h_time',  'spawn_start',  'spawn_end',  'spawn_verified', 'lat',  'lng',  
'lat_5', 'lng_5',  'distance', 'direction', 'gmaps', 'applemaps', 'pkmn_lvl',
'cp', 'iv_0', 'iv', 'iv_2',  'atk', 'def', 'sta', 'form',  'form_or_empty',  'form_id',
'form_id_3', 'quick_move', 'quick_id', 'quick_damage', 'quick_dps', 'quick_duration',
'quick_energy', 'charge_move', 'charge_id', 'charge_damage', 'charge_dps',
'charge_duration', 'charge_energy':, 'gender', 'height', 'weight', 'size'
```

### Stops

**filters**
```json 
    "stops":{
        "enabled": true,
        "defaults": {
        },
        "filters": {
            "filter-name" : {
                "min_dist": 0, "max_dist": "inf",
                "geofences": [ "Central Park" ],
                "custom_dts": { "key1": "value1", "key2": "value2" },
                "missing_info": false
            }
        }
    }
```

**dts**
```
'stop_id',  'time_left', '12h_time', '24h_time', 'lat', 'lng', 
'lat_5',  'lng_5',  'distance, 'direction',  'gmaps', 'applemaps'
```

### Gyms
**filters**
```json
"gyms":{
        "enabled": true,
        "ignore_neutral":"False",
        "defaults": {
        },
        "filters": {
            "filter-name" : {
                "min_dist": 0, "max_dist": "inf",
                "old_teams": [ "Valor", "Instinct", "Mystic" ],
                "new_teams": [ "Valor", "Instinct", "Mystic" ],
                "gym_name_matches": [ ".*" ],
                "geofences": [ "Central Park" ],
                "custom_dts": { "key1": "value1", "key2": "value2" },
                "missing_info": false
            }
        }
    },
```

**dts**
```
'gym_id', 'lat', 'lng', 'lat_5',  'lng_5',  'distance',  'direction', 'gmaps', 'applemaps', 
'old_team',  'old_team_id', 'old_team_leader', 'new_team', 'new_team_id', 
'new_team_leader',  'gym_name',  'gym_description', 'gym_image'
```

### Eggs
**filters**
```json
"eggs":{
        "enabled": true,
        "defaults": {
        },
        "filters": {
            "filter-name" : {
                "min_dist": 0, "max_dist": "inf",
                "min_egg_lvl": 0, "max_egg_lvl": 40,
                "gym_name_matches": [ ".*" ],
                "geofences": [ "Central Park" ],
                "custom_dts": { "key1": "value1", "key2": "value2" },
                "missing_info": false
            }
        }
    },
```

**dts**
```
'gym_id',  'hatch_time_left', '12h_hatch_time', '24h_hatch_time', 'raid_end', 
'12h_raid_end',  '24h_raid_end', 'lat', 'lng', 'lat_5', 'lng_5', 'distance', 'direction',
'gmaps', 'applemaps', 'egg_lvl', 'gym_name', 'gym_description', 'gym_image',  
'team_id', 'team_name', 'team_leader'
```

### Raids
**filters**
```json
    "raids":{
        "enabled": true,
        "defaults": {
        },
        "filters": {
            "filter-name" : {
                "monsters": [ 1, 2, 3 ],
                "min_dist": 0, "max_dist": "inf",
                "min_raid_lvl": 0, "max_raid_lvl": 5,
                "quick_moves": [ "Vine Whip", "Tackle"],
                "charge_moves": [ "Sludge Bomb", "Seed Bomb"],
                "gym_name_matches": [ ".*" ],
                "geofences": [ "Central Park" ],
                "custom_dts": { "key1": "value1", "key2": "value2" },
                "missing_info": false
            }
        }
    }
```
**dts**
```
'gym_id',  'time_left',  '12h_raid_end',  '24h_raid_end',  'lat',  'lng', 'lat_5', 'lng_5', 
'distance', 'direction',  'gmaps', 'applemaps',  'raid_lvl',  'mon_name', 'mon_id', 
'mon_id_3',  'quick_move',  'quick_id',  'quick_damage', 'quick_dps',  'quick_duration',
'quick_energy',  'charge_id',  'charge_damage',  'charge_dps', 'charge_duration', 
'charge_energy', 'gym_name',  'gym_description', 'gym_image',  'team_id', 
'team_name', 'team_leader'
```

### CODE REVIEW

**Comment by mali055** [comment]
You left out geofences in the filters.example btw

**Comment by kvangent** [comment]
@mali055 Thank you, I've updated it

**Comment by vincerules805** [comment]
Discord.py uses form_id_or_empty but that no longer exists. I changed it to form_or_empty and the images started working again.

**Comment by vincerules805** [comment]
I really like this new filter format but feel if you leave the geofences line empty or out it should include all geofences associated with that instance. For example I use the same raids5 filter file for multiple cities and in order for me to be able to use the <geofence> dts I need to list every geofence name for all the cities in the filter file or else it'll return unknown. Is this something that would be possible?

**Comment by kvangent** [comment]
@vincerules805 We could do it that way, but it was intentional that geofences need to be forced. By choosing which geofences are evaluated, it reduces processing power needed.

You can always added the geofence list to the defaults section and it will automatically apply to the other filters.

**Pull request merged**
